name: python-uv
targets:
  - suga/aws@1
description: "Testing a simple nitric service"
services:
  processor:
    dev:
      script: uv run uvicorn main:app --host 0.0.0.0 --port $PORT
    container:
      docker:
        dockerfile: Dockerfile
        context: .
entrypoints:
  ingress:
    routes:
      /:
        name: processor
buckets:
  image:
    access:
      processor:
        - all
