targets:
  - suga/aws@1
name: python-django
description: Testing a simple nitric service
services:
  processor:
    container:
      docker:
        dockerfile: Dockerfile
        context: .
    dev:
      script: python manage.py runserver 0.0.0.0:$PORT
buckets:
  image:
    access:
      processor:
        - all
entrypoints:
  ingress:
    routes:
      /:
        name: processor
